pipelines:
  pull-requests:
    '**':
      - step:
          name: Identify Changed Feature Files
          script:
            - apt-get update && apt-get install -y git
            - echo "Identifying changed files..."
            - export local_branch="${BITBUCKET_BRANCH}"
            - export target_branch="main"
            - export CHANGED_FILES=$(git diff --name-only origin/$target_branch...$local_branch -- cypress/integration)
            - echo "------------------------------------"
            - echo "Changed files:"
            - echo "$CHANGED_FILES"
            - echo "------------------------------------"
            - echo "$CHANGED_FILES" > changed_files.txt
            - |
              if [ -z "$CHANGED_FILES" ]; then
                echo "No Cypress test files changed. Skipping test execution."
                exit 0
              else
                echo "Proceeding to run tests for the changed files."
              fi
          artifacts:
            - changed_files.txt

      - step:
          name: Run test only for affected files
          image: cypress/browsers:node-22.7.0-chrome-127.0.6533.119-1-ff-129.0.1-edge-127.0.2651.98-1
          caches:
            - node
          script:
            - echo "Preparing to run Cypress tests..."
            - npm ci
            - npx cypress verify
            - CHANGED_FILES=$(cat changed_files.txt)
            - echo $CHANGED_FILES
            - |
              if [ -n "$CHANGED_FILES" ]; then
                FILES=$(echo "$CHANGED_FILES" | tr '\n' ',')
                FILES=$(echo "$FILES" | sed 's/,$//')
                echo "Running Cypress with the following spec files: $FILES"  
                NO_COLOR=1 npx cypress run --headless --browser chrome --env configFile=env-stage --spec "$FILES"
              else
                echo "No files to test."
                exit 0
              fi
          artifacts:
            - cypress/reports/allure-results/**

  branches:
    main:
      - step:
          name: Run Cypress Tests on Master
          image: cypress/browsers:node-22.7.0-chrome-127.0.6533.119-1-ff-129.0.1-edge-127.0.2651.98-1
          caches:
            - node
          script:
            - echo "Running Cypress tests on master branch..."
            - npm ci
            - npx cypress verify
            - NO_COLOR=1 npx cypress run --headless --browser chrome --env configFile=env-stage
            - npm run allure:report
          artifacts:
            - cypress/reports/allure-report/**

  custom:
    trigger-cypress-tests:
      - step:
          name: Run Cypress Tests from Webhook
          image: cypress/browsers:node-22.7.0-chrome-127.0.6533.119-1-ff-129.0.1-edge-127.0.2651.98-1
          caches:
            - node
          script:
            - echo "Running Cypress tests triggered by webhook..."
            - npm ci
            - npx cypress verify
            - NO_COLOR=1 npx cypress run --headless --browser chrome --env configFile=env-stage
            - npm run allure generate cypress/reports/allure-results --clean -o cypress/reports/allure-report
          artifacts:
            - cypress/reports/allure-report/**